import { expect, test } from '@playwright/test'

test('카드 소개의 구분·제출 후 강조를 이동과 새로고침 뒤 유지한다', async ({ page }, info) => {
  await page.goto('/learn/part-0/goal-and-cards?restart=1')
  await expect(page.getByRole('group', { name: '내 개인 카드' }).locator('.playing-card')).toHaveCount(2)
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await expect(page.getByRole('group', { name: '플랍 · 처음 3장' }).locator('.playing-card')).toHaveCount(3)
  await expect(page.getByRole('group', { name: '턴 · 1장 추가' }).locator('.playing-card')).toHaveCount(1)
  await expect(page.getByRole('group', { name: '리버 · 1장 추가' }).locator('.playing-card')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('community-groups.png'), fullPage: true })
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await expect(page.locator('.poker-table__highlight')).toHaveCount(0)
  await page.getByRole('radio', { name: '5장', exact: true }).check()
  await page.getByRole('button', { name: '정답 확인' }).click()
  await expect(page.locator('.poker-table__highlight')).toHaveCount(5)
  await page.reload()
  await expect(page.getByRole('radio', { name: '5장', exact: true })).toBeChecked()
  await expect(page.locator('.poker-table__highlight')).toHaveCount(5)
  await page.getByRole('button', { name: '이전', exact: true }).click()
  await expect(page.getByRole('group', { name: '플랍 · 처음 3장' })).toBeVisible()
})

test('행동과 자리 도식은 모바일에서도 넘치지 않고 정답을 미리 표시하지 않는다', async ({ page }, info) => {
  await page.goto('/learn/part-0/player-actions?restart=1')
  await expect(page.getByRole('group', { name: '상대는 10칩을 걸었고, 나는 아직 칩을 내지 않았어요' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('actions.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/learn/part-0/blinds-and-order?restart=1')
  await expect(page.locator('.rule-seat')).toHaveCount(6)
  await page.screenshot({ path: info.outputPath('blinds.png'), fullPage: true })
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await expect(page.getByRole('group', { name: '플레이어 4 · 먼저 행동' })).toBeVisible()
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await expect(page.getByText('먼저 행동', { exact: true })).toHaveCount(0)
  await page.getByRole('radio', { name: '딜러 버튼 왼쪽의 남아 있는 플레이어', exact: true }).check()
  await page.getByRole('button', { name: '정답 확인' }).click()
  await expect(page.getByRole('group', { name: 'SB · 먼저 행동' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('group', { name: 'SB · 먼저 행동' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
