import { expect, test } from '@playwright/test'

test('Part 1 복수 선택 복원·오답 리뷰·완료 후 새 시작을 확인한다', async ({ page }) => {
  await page.goto('/parts/part-1')
  await expect(page.locator('.lesson-practice-link')).toHaveCount(5)
  await page.getByRole('link', { name: '카드 특징 찾아내기 · 추가 연습', exact: true }).click()
  await page.getByRole('button', { name: '연습 시작', exact: true }).click()
  await expect(page.locator('.practice-hands .playing-card')).toHaveCount(2)
  const labels = await page.getByRole('checkbox').evaluateAll(inputs => inputs.map(input => input.parentElement!.textContent!))
  for (const checkbox of await page.getByRole('checkbox').all()) await checkbox.check()
  await page.getByRole('button', { name: '정답 확인' }).click()
  const feedback = await page.getByRole('status').textContent()
  await page.reload()
  await page.getByRole('button', { name: '이어서 연습하기' }).click()
  for (const label of labels) await expect(page.getByRole('checkbox', { name: label, exact: true })).toBeChecked()
  await expect(page.getByRole('status')).toHaveText(feedback!)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '1')
  await page.getByRole('link', { name: '← Part 1로 돌아가기', exact: true }).click()
  await page.getByRole('link', { name: '← 홈', exact: true }).click()
  await page.goto('/parts/part-1')
  await page.getByRole('link', { name: '카드 특징 찾아내기 · 추가 연습', exact: true }).click()
  await page.getByRole('button', { name: '이어서 연습하기' }).click()
  await expect(page.getByRole('status')).toHaveText(feedback!)
  await page.getByRole('button', { name: '다음', exact: true }).click()
  for (let i = 1; i < 4; i++) {
    await page.getByRole('checkbox').first().check()
    await page.getByRole('button', { name: '정답 확인' }).click()
    await page.getByRole('button', { name: i === 3 ? '완료' : '다음', exact: true }).click()
  }
  await expect(page.getByRole('heading', { name: '추가 연습을 마쳤어요' })).toBeVisible()
  await page.locator('.practice-result summary').first().click()
  await expect(page.locator('.practice-result details').first().getByText(/^내 선택:/)).toContainText('포켓 페어')
  await expect(page.locator('.practice-result details').first().getByText(/^내 선택:/)).toContainText('수딧')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('part1-practice-review.png'), fullPage: true })
  await page.getByRole('link', { name: '← Part 1로 돌아가기', exact: true }).click()
  await page.getByRole('link', { name: '카드 특징 찾아내기 · 추가 연습', exact: true }).click()
  await expect(page.getByRole('button', { name: '연습 시작', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '추가 연습을 마쳤어요' })).toHaveCount(0)
})

test('Part 1 각 연습의 카드·포지션과 종합 여섯 문제를 표시한다', async ({ page }) => {
  for (const id of ['compare-hands', 'classify-strength', 'same-hand-different-position', 'starting-hand-challenge']) {
    await page.goto(`/practice/part-1/${id}`)
    await page.getByRole('button', { name: '연습 시작', exact: true }).click()
    await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuemax', id === 'starting-hand-challenge' ? '6' : '4')
    if (id === 'compare-hands') await expect(page.locator('.practice-hands .playing-card')).toHaveCount(4)
    if (id === 'classify-strength') await expect(page.getByRole('radio')).toHaveCount(2)
    if (id === 'same-hand-different-position') await expect(page.locator('[aria-current]')).toHaveCount(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (id === 'starting-hand-challenge') {
      for (let i = 0; i < 6; i++) {
        const checkboxes = page.getByRole('checkbox')
        if (await checkboxes.count()) await checkboxes.first().check()
        else await page.getByRole('radio').first().check()
        await page.getByRole('button', { name: '정답 확인' }).click()
        await page.getByRole('button', { name: i === 5 ? '완료' : '다음', exact: true }).click()
      }
      await expect(page.getByRole('heading', { name: '종합 연습을 마쳤어요' })).toBeVisible()
    }
  }
})

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
})

test('선택과 제출한 해설을 새로고침 뒤에도 같은 문제에 복원한다', async ({ page }) => {
  await page.goto('/parts/part-2')
  const lessonRow = page.getByRole('listitem').filter({ has: page.getByText('원 페어의 위치 구분하기', { exact: true }) })
  await expect(lessonRow.getByRole('link', { name: '원 페어의 위치 구분하기 · 추가 연습', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('part2-lesson-list.png'), fullPage: true })
  await page.getByRole('link', { name: '원 페어의 위치 구분하기 · 추가 연습', exact: true }).click()
  await page.getByRole('button', { name: '연습 시작', exact: true }).click()
  const label = await page.getByRole('radio').first().locator('..').textContent()
  await page.getByRole('radio').first().check()
  const saved = await page.evaluate(() => localStorage.getItem('holdem-practice-progress'))
  await page.reload()
  await page.getByRole('button', { name: '이어서 연습하기' }).click()
  await expect(page.getByRole('radio', { name: label!, exact: true })).toBeChecked()
  expect(await page.evaluate(() => localStorage.getItem('holdem-practice-progress'))).toBe(saved)
  await page.getByRole('button', { name: '정답 확인' }).click()
  const feedback = await page.getByRole('status').textContent()
  await page.reload()
  await page.getByRole('button', { name: '이어서 연습하기' }).click()
  await expect(page.getByRole('status')).toHaveText(feedback!)
  await expect(page.getByRole('radio', { name: label!, exact: true })).toBeChecked()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '1')
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await page.getByRole('button', { name: '이전', exact: true }).click()
  await expect(page.getByRole('radio', { name: label!, exact: true })).toBeChecked()
  const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth }))
  expect(size.content).toBeLessThanOrEqual(size.viewport)
  await page.screenshot({ path: test.info().outputPath('practice-screen.png'), fullPage: true })
})

test('회차 완료 후 다른 문제를 뽑고 레슨 진도는 바꾸지 않는다', async ({ page }) => {
  await page.goto('/practice/part-2/pair-types')
  const lessonBefore = await page.evaluate(() => localStorage.getItem('holdem-learning-progress'))
  await page.getByRole('button', { name: '연습 시작', exact: true }).click()
  const firstIds = await page.evaluate(() => JSON.parse(localStorage.getItem('holdem-practice-progress')!).sessions['pair-types'].questionIds as string[])
  for (let i = 0; i < 4; i++) {
    await page.getByRole('radio').first().check()
    await page.getByRole('button', { name: '정답 확인' }).click()
    await page.getByRole('button', { name: i === 3 ? '완료' : '다음', exact: true }).click()
  }
  await expect(page.getByRole('heading', { name: '추가 연습을 마쳤어요' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('holdem-learning-progress'))).toBe(lessonBefore)
  await page.getByRole('button', { name: '새 문제로 연습하기' }).click()
  const nextIds = await page.evaluate(() => JSON.parse(localStorage.getItem('holdem-practice-progress')!).sessions['pair-types'].questionIds as string[])
  expect(nextIds.some(id => firstIds.includes(id))).toBe(false)
  await expect(page.getByRole('radio').first()).not.toBeChecked()
  await page.getByRole('link', { name: '← Part 2로 돌아가기', exact: true }).click()
  await page.getByRole('link', { name: '원 페어의 위치 구분하기 · 추가 연습', exact: true }).click()
  await page.getByRole('button', { name: '새 문제로 연습하기' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '취소', exact: true }).click()
  const retainedIds = await page.evaluate(() => JSON.parse(localStorage.getItem('holdem-practice-progress')!).sessions['pair-types'].questionIds as string[])
  expect(retainedIds).toEqual(nextIds)
})

test('문제를 이동하면 카드와 문제 시작을 바로 볼 수 있다', async ({ page }) => {
  await page.goto('/practice/part-2/read-current-hand')
  await expect(page.locator('header').getByRole('button', { name: '연습 시작', exact: true })).toBeVisible()
  await expect(page.locator('.message-panel')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('practice-start.png'), fullPage: true })
  await page.getByRole('button', { name: '연습 시작', exact: true }).click()
  for (let i = 0; i < 2; i++) {
    await page.getByRole('radio').first().check()
    await page.getByRole('button', { name: '정답 확인' }).click()
    await page.getByRole('button', { name: '다음', exact: true }).click()
    await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', String(i + 2))
    await expect.poll(async () => (await page.locator('.learning-session').boundingBox())!.y).toBeGreaterThanOrEqual(0)
    await expect.poll(async () => (await page.locator('.learning-session').boundingBox())!.y).toBeLessThan(page.viewportSize()!.height)
    await expect.poll(async () => (await page.locator('.poker-table').boundingBox())!.y).toBeGreaterThanOrEqual(0)
    await expect.poll(async () => (await page.locator('.poker-table').boundingBox())!.y).toBeLessThan(page.viewportSize()!.height)
    await expect(page.getByRole('button', { name: '연습 잠시 나가기' })).toHaveCount(0)
  }
  await page.getByRole('button', { name: '이전', exact: true }).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '2')
  await expect.poll(async () => (await page.locator('.poker-table').boundingBox())!.y).toBeGreaterThanOrEqual(0)
  await expect.poll(async () => (await page.locator('.poker-table').boundingBox())!.y).toBeLessThan(page.viewportSize()!.height)
  await page.screenshot({ path: test.info().outputPath('practice-next-question.png') })
})

test('다섯 레슨은 네 문제, 종합 연습은 여섯 문제로 열린다', async ({ page }) => {
  for (const id of ['preflop-to-flop', 'read-current-hand', 'two-pair-and-set', 'board-and-risk', 'flop-reading-challenge']) {
    await page.goto(`/practice/part-2/${id}`)
    await page.getByRole('button', { name: '연습 시작', exact: true }).click()
    await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuemax', id === 'flop-reading-challenge' ? '6' : '4')
    await expect(page.getByRole('radio').first()).toBeVisible()
  }
})
